-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 21:47:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Apartamento` (
  `idApartamento` INT NOT NULL AUTO_INCREMENT,
  `Bloco` INT NOT NULL,
  `fk_NumeroApartamento` INT NOT NULL,
  `fk_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idApartamento`),
  UNIQUE INDEX `id_Apartamento_UNIQUE` (`idApartamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Telefone` VARCHAR(30) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `NumeroApartamento` INT NOT NULL,
  `fk_idApartamento` INT NOT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_Pessoa_Apartamento_idx` (`fk_idApartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Apartamento`
    FOREIGN KEY (`fk_idApartamento`)
    REFERENCES `default_schema`.`Apartamento` (`idApartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`TipoPessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`TipoPessoa` (
  `idPessoa` INT NOT NULL,
  `TipoPessoa` VARCHAR(20) NOT NULL,
  `DescricaoPessoa` VARCHAR(90) NULL DEFAULT NULL,
  `fk_idPessoa` INT NOT NULL,
  PRIMARY KEY (`TipoPessoa`),
  INDEX `fk_TipoPessoa_Pessoa1_idx` (`fk_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_TipoPessoa_Pessoa1`
    FOREIGN KEY (`fk_idPessoa`)
    REFERENCES `default_schema`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`TipoCusto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`TipoCusto` (
  `TipoCusto` VARCHAR(15) NOT NULL,
  `DescricaoCusto` VARCHAR(90) NULL DEFAULT NULL,
  PRIMARY KEY (`TipoCusto`),
  UNIQUE INDEX `TipoCusto_UNIQUE` (`TipoCusto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Cobranca` (
  `idCobranca` INT NOT NULL AUTO_INCREMENT,
  `Valor` FLOAT NOT NULL,
  `Data` DATE NOT NULL,
  `Quitado` TINYINT NOT NULL,
  `fk_idPessoa` INT NOT NULL,
  `fk_TipoCusto` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `idCobranca_UNIQUE` (`idCobranca` ASC) VISIBLE,
  PRIMARY KEY (`idCobranca`),
  INDEX `fk_Cobranca_Pessoa1_idx` (`fk_idPessoa` ASC) VISIBLE,
  INDEX `fk_Cobranca_TipoCusto1_idx` (`fk_TipoCusto` ASC) VISIBLE,
  CONSTRAINT `fk_Cobranca_Pessoa1`
    FOREIGN KEY (`fk_idPessoa`)
    REFERENCES `default_schema`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cobranca_TipoCusto1`
    FOREIGN KEY (`fk_TipoCusto`)
    REFERENCES `default_schema`.`TipoCusto` (`TipoCusto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
